
datastore:
  datastoreBackend:
    imgTag: v35.0
    replicaCount: 1
    containerResources:
      requests:
        cpu: 100m
        memory: "500Mi"
      limits:
        cpu: 1
        memory: "1Gi"
    healthChecks:
      livenessProbe:
        httpGet:
          path: /actuator
          port: 8084
        initialDelaySeconds: 20
        periodSeconds: 3
        timeoutSeconds: 4
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /actuator
          port: 8084
        initialDelaySeconds: 20
        periodSeconds: 3
        timeoutSeconds: 4
        failureThreshold: 3
      startupProbe:
        httpGet:
          path: /actuator
          port: 8084
        initialDelaySeconds: 20
        periodSeconds: 3
        timeoutSeconds: 4
        failureThreshold: 3