apiVersion: v1
kind: ConfigMap
metadata:
  name: datastore-be-cm
  namespace: backend
data:
  mysqlHost: jdbc:mysql://datastore.cdylzzu6vrk0.us-east-1.rds.amazonaws.com:3306/datastore?createDatabaseIfNotExist=true
  mysqlUname: root